name: Feature request
description: Suggest an idea
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: "Given ... When ... Then ..."
