name: Issue Metrics

on:
  schedule:
    - cron: "0 7 * * 1-5"   # 07:00 UTC on weekdays
  workflow_dispatch:

# Needed so the workflow can open an issue for the report
permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Set time window (last 7 days)
        shell: bash
        run: |
          echo "SINCE=$(date -u -d '7 days ago' +%Y-%m-%d)" >> $GITHUB_ENV
          echo "TODAY=$(date -u +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Run issue-metrics
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Adjust the query as needed:
          #  - created:>=SINCE (new issues opened in window)
          #  - updated:>=SINCE (activity in window)
          SEARCH_QUERY: 'repo:${{ github.repository }} is:issue created:>=${{ env.SINCE }}'

      - name: Publish report as issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Issue metrics report (${{ env.SINCE }} → ${{ env.TODAY }})"
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          labels: "team-metrics"
